create table if not exists public.users (
    id bigint generated by default as identity primary key,
    name text not null,
    email text unique,
    username text,
    password_hash text not null,
    profile_picture text default 'default.png',
    role text default 'student',
    is_active boolean not null default true,
    last_login_at timestamptz,
    must_change_password boolean not null default false
);

alter table public.users
    add column if not exists is_active boolean not null default true;
alter table public.users
    add column if not exists last_login_at timestamptz;
alter table public.users
    add column if not exists must_change_password boolean not null default false;
alter table public.users
    add column if not exists username text;
alter table public.users
    alter column email drop not null;
create unique index if not exists users_username_lower_unique on public.users (lower(username)) where username is not null;

create table if not exists public.system_settings (
    settings_key text primary key,
    settings_json text not null,
    updated_by bigint references public.users(id) on delete set null,
    updated_at timestamptz not null default current_timestamp
);

create table if not exists public.admin_activity_logs (
    id bigint generated by default as identity primary key,
    actor_user_id bigint references public.users(id) on delete set null,
    actor_name text not null default '',
    actor_email text not null default '',
    action text not null,
    target_user_id bigint,
    target_label text not null default '',
    details text not null default '',
    session_ip text not null default '',
    created_at timestamptz not null default current_timestamp
);

alter table public.admin_activity_logs
    add column if not exists session_ip text not null default '';

create table if not exists public.report_card_uploads (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    original_filename text not null,
    content_type text not null,
    file_data bytea not null,
    uploaded_at timestamptz not null default current_timestamp,
    ocr_status text not null default 'needs_review',
    is_flagged boolean not null default false,
    flag_note text,
    student_name text not null default '',
    student_number text not null default '',
    extracted_subjects text not null default '',
    extracted_gwa text not null default '',
    ocr_error text,
    processed_at timestamptz
);

alter table public.report_card_uploads
    add column if not exists ocr_status text not null default 'needs_review',
    add column if not exists is_flagged boolean not null default false,
    add column if not exists flag_note text,
    add column if not exists student_name text not null default '',
    add column if not exists student_number text not null default '',
    add column if not exists extracted_subjects text not null default '',
    add column if not exists extracted_gwa text not null default '',
    add column if not exists ocr_error text,
    add column if not exists processed_at timestamptz;

create table if not exists public.student_profiles (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    student_number text,
    first_name text,
    middle_initial text,
    last_name text,
    course text,
    gwa text,
    subjects text,
    recommendation text,
    strand text,
    upload_date text,
    grades text,
    report_card_upload_id bigint references public.report_card_uploads(id) on delete set null
);

alter table public.student_profiles
    add column if not exists report_card_upload_id bigint
    references public.report_card_uploads(id) on delete set null;

create table if not exists public.course_recommendation_history (
    id bigint generated by default as identity primary key,
    profile_id bigint not null references public.student_profiles(id) on delete cascade,
    recommendations text not null,
    generated_at timestamptz not null default current_timestamp
);

insert into public.course_recommendation_history (profile_id, recommendations)
select profiles.id, profiles.recommendation
from public.student_profiles profiles
where profiles.recommendation is not null and profiles.recommendation != ''
    and not exists (
        select 1 from public.course_recommendation_history history
        where history.profile_id = profiles.id
    );

create index if not exists student_profiles_user_id_idx
    on public.student_profiles(user_id);

create table if not exists public.university_courses (
    id bigint generated by default as identity primary key,
    course text not null unique,
    features jsonb not null,
    description text not null
);
alter table public.university_courses drop column if exists training_course;
alter table public.university_courses drop column if exists description_override;
alter table public.university_courses add column if not exists features jsonb;
alter table public.university_courses add column if not exists description text;
delete from public.university_courses;
insert into public.university_courses (course, features, description) values
('BS in Medical Technology', '[82, 92, 76, 62, 68, 72]', 'Train for clinical laboratory diagnostics, biomedical testing, and healthcare support services.'),
('BS in Nursing', '[80, 90, 79, 60, 70, 74]', 'Prepare for patient-centered healthcare work through science, compassion, and clinical excellence.'),
('BS in Occupational Therapy', '[81, 96, 75, 59, 63, 78]', 'Prepare for patient-centered careers through functional rehabilitation for daily living skills.'),
('BS in Pharmacy', '[84, 91, 78, 66, 71, 72]', 'Study medicines, therapeutics, and patient care with a strong chemistry and biology foundation.'),
('BS in Physical Therapy', '[80, 89, 81, 63, 64, 74]', 'Prepare for patient-centered careers through movement rehabilitation and physical recovery.'),
('BS in Radiologic Technology', '[80, 94, 74, 68, 62, 72]', 'Use imaging technology and patient care knowledge to support diagnosis and medical procedures.'),
('BS in Respiratory Therapy', '[82, 93, 75, 68, 65, 72]', 'Support respiratory health through medical science, patient assessment, and therapeutic interventions.'),
('BS in Architecture', '[82, 86, 80, 66, 68, 72]', 'Design built environments and space planning with a balance of creativity, technical drawing, and problem solving.'),
('Bachelor of Arts in Communication', '[69, 77, 93, 64, 71, 91]', 'Study media, journalism, and public communication to prepare for community-focused and academic careers.'),
('Bachelor of Arts major in Political Science', '[70, 76, 90, 60, 84, 82]', 'Study governance, public policy, and civic systems with strong communication and analysis abilities.'),
('Bachelor of Arts in Psychology', '[82, 78, 90, 60, 70, 75]', 'Study human behavior, mental processes, and social interactions in academic and applied settings.'),
('Bachelor of Arts in Multimedia Arts', '[83, 71, 72, 99, 73, 71]', 'Build practical skills in digital media production across platforms for modern technology-driven careers.'),
('Bachelor of Science in Psychology', '[82, 78, 90, 60, 70, 75]', 'Study human behavior, mental processes, and social interactions in academic and applied settings.'),
('BS in Aircraft Maintenance and Technology', '[91, 93, 77, 66, 61, 71]', 'Study aircraft inspection, maintenance, and repair for safe aviation operations.'),
('BS in Aviation Electronics Technology', '[90, 94, 76, 72, 62, 70]', 'Study aircraft electrical systems, avionics, and aviation electronics maintenance.'),
('Aircraft Maintenance Technology', '[91, 93, 77, 66, 61, 71]', 'Study aircraft inspection, maintenance, and repair for safe aviation operations.'),
('Aviation Electronics Technology', '[90, 94, 76, 72, 62, 70]', 'Study aircraft electrical systems, avionics, and aviation electronics maintenance.'),
('BS in Accountancy', '[79, 70, 78, 64, 97, 70]', 'Build expertise in financial reporting, auditing, taxation, and strategic business accounting.'),
('BS in Business Administration', '[72, 68, 82, 65, 95, 70]', 'Learn leadership, operations, and management with a strong foundation in business strategy and communication.'),
('BS in Business Administration major in Human Resource Management', '[67, 70, 84, 65, 96, 69]', 'Develop workforce planning and organizational development expertise for leadership roles in modern organizations.'),
('BS in Business Administration major in Marketing Management', '[70, 66, 84, 62, 95, 74]', 'Develop strong communication and market-analysis skills to create customer-focused business strategies.'),
('BS in Entrepreneurship', '[75, 65, 87, 66, 99, 69]', 'Develop business creation and venture management expertise for leadership roles in modern organizations.'),
('BS in Criminology', '[70, 79, 90, 58, 76, 88]', 'Examine crime, justice systems, and social behavior with strong analytical and communication skills.'),
('BS in Aeronautical Engineering', '[93, 91, 76, 68, 66, 70]', 'Apply engineering principles and technical design to solve real-world aircraft and spacecraft systems design challenges.'),
('BS in Civil Engineering', '[90, 95, 78, 60, 60, 72]', 'Build infrastructure and solve large-scale engineering challenges in construction and public works.'),
('BS in Mechanical Engineering', '[91, 93, 77, 66, 61, 71]', 'Focus on machines, manufacturing systems, and thermodynamics for industrial problem solving.'),
('BS in Computer Engineering', '[91, 95, 81, 72, 65, 68]', 'Apply engineering principles and technical design to solve real-world hardware, embedded systems, and computing infrastructure challenges.'),
('BS in Digital Engineering', '[83, 75, 78, 95, 64, 68]', 'Apply digital tools, data, and engineering methods to design technical systems.'),
('BS in Electrical Engineering', '[90, 94, 76, 72, 62, 70]', 'Work with circuits, power systems, electronics, and control technologies.'),
('BS in Electronics Engineering major in Biomedical Engineering', '[92, 92, 76, 72, 63, 69]', 'Apply engineering principles and technical design to solve real-world medical devices and healthcare technology challenges.'),
('BS in Industrial Engineering', '[90, 93, 80, 67, 57, 63]', 'Apply engineering principles and technical design to solve real-world manufacturing systems and process optimization challenges.'),
('BS in Information Technology with Specialization in Game Development', '[83, 75, 75, 89, 72, 66]', 'Build practical skills in interactive game design and programming for modern technology-driven careers.'),
('BS in Computer Science with Specialization in Data Science', '[90, 84, 80, 92, 72, 74]', 'Combine statistics, analytics, and programming to extract insights and build data-driven solutions.'),
('Bachelor of Library and Information Science', '[84, 78, 81, 93, 71, 61]', 'Build practical skills in organizing and managing information resources for modern technology-driven careers.'),
('BS in Tourism Management', '[68, 72, 88, 62, 92, 84]', 'Prepare for service, hospitality, and destination management roles in the travel and tourism sector.'),
('BS in Hospitality Management', '[68, 72, 86, 63, 94, 82]', 'Train for service operations, guest relations, and leadership within hotels, events, and tourism enterprises.'),
('BS in Marine Transportation', '[69, 80, 84, 57, 90, 84]', 'Prepare for maritime navigation and ship operations careers serving communities and institutions.'),
('BS in Marine Engineering', '[93, 92, 73, 64, 58, 66]', 'Apply engineering principles and technical design to solve real-world ship propulsion and onboard mechanical systems challenges.'),
('BS in Naval Architecture and Marine Engineering', '[92, 96, 80, 63, 58, 65]', 'Study ship design, vessel structures, and marine engineering systems.'),
('Bachelor of Early Childhood Education', '[74, 82, 92, 58, 66, 88]', 'Guide young learners through developmental, emotional, and literacy-based education practices.'),
('Bachelor of Elementary Education', '[74, 82, 92, 58, 66, 88]', 'Prepare to teach and support learners across elementary school subjects.'),
('Bachelor of Physical Education', '[73, 69, 91, 59, 66, 90]', 'Study teaching physical fitness and sports education to prepare for community-focused and academic careers.'),
('Bachelor of Secondary Education', '[77, 76, 92, 64, 69, 87]', 'Prepare to teach and support learners at the secondary school level.'),
('Bachelor of Special Needs Education', '[71, 79, 88, 57, 68, 85]', 'Study inclusive teaching for learners with special needs to prepare for community-focused and academic careers.');
alter table public.university_courses alter column features set not null;
alter table public.university_courses alter column description set not null;

create table if not exists public.university_course_strands (
    course text not null references public.university_courses(course) on delete cascade,
    strand_code text not null check (strand_code in (
        'ABM', 'STEM', 'HUMSS', 'GAS', 'TVL', 'TVL_ICT', 'TVL_HE', 'TVL_IA', 'ARTS_DESIGN', 'SPORTS'
    )),
    primary key (course, strand_code)
);
delete from public.university_course_strands;
insert into public.university_course_strands (course, strand_code) values
('BS in Accountancy', 'ABM'),
('BS in Business Administration', 'ABM'),
('BS in Business Administration major in Human Resource Management', 'ABM'),
('BS in Business Administration major in Marketing Management', 'ABM'),
('BS in Entrepreneurship', 'ABM'),
('BS in Medical Technology', 'STEM'),
('BS in Nursing', 'STEM'),
('BS in Occupational Therapy', 'STEM'),
('BS in Pharmacy', 'STEM'),
('BS in Physical Therapy', 'STEM'),
('BS in Radiologic Technology', 'STEM'),
('BS in Respiratory Therapy', 'STEM'),
('BS in Architecture', 'STEM'),
('BS in Aeronautical Engineering', 'STEM'),
('BS in Civil Engineering', 'STEM'),
('BS in Mechanical Engineering', 'STEM'),
('BS in Computer Engineering', 'STEM'),
('BS in Digital Engineering', 'STEM'),
('BS in Electrical Engineering', 'STEM'),
('BS in Electronics Engineering major in Biomedical Engineering', 'STEM'),
('BS in Industrial Engineering', 'STEM'),
('BS in Marine Engineering', 'STEM'),
('BS in Naval Architecture and Marine Engineering', 'STEM'),
('BS in Computer Science with Specialization in Data Science', 'STEM'),
('BS in Aircraft Maintenance and Technology', 'STEM'),
('BS in Aviation Electronics Technology', 'STEM'),
('Aircraft Maintenance Technology', 'STEM'),
('Aviation Electronics Technology', 'STEM'),
('Bachelor of Arts in Communication', 'HUMSS'),
('Bachelor of Arts major in Political Science', 'HUMSS'),
('Bachelor of Arts in Psychology', 'HUMSS'),
('Bachelor of Science in Psychology', 'HUMSS'),
('Bachelor of Arts in Multimedia Arts', 'HUMSS'),
('BS in Criminology', 'HUMSS'),
('Bachelor of Early Childhood Education', 'HUMSS'),
('Bachelor of Elementary Education', 'HUMSS'),
('Bachelor of Secondary Education', 'HUMSS'),
('Bachelor of Special Needs Education', 'HUMSS'),
('BS in Information Technology with Specialization in Game Development', 'TVL_ICT'),
('BS in Hospitality Management', 'TVL_HE'),
('BS in Nursing', 'TVL_HE'),
('BS in Medical Technology', 'TVL_HE'),
('Bachelor of Arts in Multimedia Arts', 'ARTS_DESIGN'),
('BS in Architecture', 'ARTS_DESIGN'),
('Bachelor of Arts in Communication', 'ARTS_DESIGN'),
('Bachelor of Physical Education', 'SPORTS');

insert into public.university_course_strands (course, strand_code)
select distinct course, 'TVL'
from public.university_course_strands
where strand_code in ('TVL_ICT', 'TVL_HE', 'TVL_IA')
on conflict (course, strand_code) do nothing;

drop table if exists public.course_training_data;
