create table if not exists public.users (
    id bigint generated by default as identity primary key,
    name text not null,
    email text not null unique,
    password_hash text not null,
    profile_picture text default 'default.png',
    role text default 'student',
    is_active boolean not null default true,
    last_login_at timestamptz,
    must_change_password boolean not null default false
);

alter table public.users
    add column if not exists is_active boolean not null default true;
alter table public.users
    add column if not exists last_login_at timestamptz;
alter table public.users
    add column if not exists must_change_password boolean not null default false;

create table if not exists public.system_settings (
    settings_key text primary key,
    settings_json text not null,
    updated_by bigint references public.users(id) on delete set null,
    updated_at timestamptz not null default current_timestamp
);

create table if not exists public.admin_activity_logs (
    id bigint generated by default as identity primary key,
    actor_user_id bigint references public.users(id) on delete set null,
    actor_name text not null default '',
    actor_email text not null default '',
    action text not null,
    target_user_id bigint,
    target_label text not null default '',
    details text not null default '',
    session_ip text not null default '',
    created_at timestamptz not null default current_timestamp
);

alter table public.admin_activity_logs
    add column if not exists session_ip text not null default '';

create table if not exists public.report_card_uploads (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    original_filename text not null,
    content_type text not null,
    file_data bytea not null,
    uploaded_at timestamptz not null default current_timestamp,
    ocr_status text not null default 'needs_review',
    is_flagged boolean not null default false,
    flag_note text,
    student_name text not null default '',
    student_number text not null default '',
    extracted_subjects text not null default '',
    extracted_gwa text not null default '',
    ocr_error text,
    processed_at timestamptz
);

alter table public.report_card_uploads
    add column if not exists ocr_status text not null default 'needs_review',
    add column if not exists is_flagged boolean not null default false,
    add column if not exists flag_note text,
    add column if not exists student_name text not null default '',
    add column if not exists student_number text not null default '',
    add column if not exists extracted_subjects text not null default '',
    add column if not exists extracted_gwa text not null default '',
    add column if not exists ocr_error text,
    add column if not exists processed_at timestamptz;

create table if not exists public.student_profiles (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    student_number text,
    first_name text,
    middle_initial text,
    last_name text,
    course text,
    gwa text,
    subjects text,
    recommendation text,
    strand text,
    upload_date text,
    grades text,
    report_card_upload_id bigint references public.report_card_uploads(id) on delete set null
);

alter table public.student_profiles
    add column if not exists report_card_upload_id bigint
    references public.report_card_uploads(id) on delete set null;

create table if not exists public.course_recommendation_history (
    id bigint generated by default as identity primary key,
    profile_id bigint not null references public.student_profiles(id) on delete cascade,
    recommendations text not null,
    generated_at timestamptz not null default current_timestamp
);

insert into public.course_recommendation_history (profile_id, recommendations)
select profiles.id, profiles.recommendation
from public.student_profiles profiles
where profiles.recommendation is not null and profiles.recommendation != ''
    and not exists (
        select 1 from public.course_recommendation_history history
        where history.profile_id = profiles.id
    );

create index if not exists student_profiles_user_id_idx
    on public.student_profiles(user_id);

create table if not exists public.course_training_data (
    id bigint generated by default as identity primary key,
    course text not null unique,
    features jsonb not null,
    description text not null
);

insert into public.course_training_data (course, features, description) values
('Computer Science', '[85, 75, 80, 95, 65, 70]', 'Design software systems, build applications, and work in technology-driven industries with strong problem-solving skills.'),
('Information Technology', '[78, 72, 78, 90, 70, 68]', 'Focus on networking, systems administration, and practical technology support for modern organizations.'),
('Information Systems', '[76, 72, 80, 86, 82, 72]', 'Bridge business and technology by designing systems that support organizational goals and decision making.'),
('Data Science', '[90, 84, 80, 92, 72, 74]', 'Combine statistics, analytics, and programming to extract insights and build data-driven solutions.'),
('Software Engineering', '[84, 76, 81, 94, 70, 71]', 'Apply engineering practices to software design, testing, quality assurance, and delivery.'),
('Business Administration', '[72, 68, 82, 65, 95, 70]', 'Learn leadership, operations, and management with a strong foundation in business strategy and communication.'),
('Accountancy', '[79, 70, 78, 64, 97, 70]', 'Build expertise in financial reporting, auditing, taxation, and strategic business accounting.'),
('Marketing Management', '[70, 66, 84, 62, 95, 74]', 'Develop strong communication and market-analysis skills to create customer-focused business strategies.'),
('Nursing', '[80, 90, 79, 60, 70, 74]', 'Prepare for patient-centered healthcare work through science, compassion, and clinical excellence.'),
('Medical Technology', '[82, 92, 76, 62, 68, 72]', 'Train for clinical laboratory diagnostics, biomedical testing, and healthcare support services.'),
('Pharmacy', '[84, 91, 78, 66, 71, 72]', 'Study medicines, therapeutics, and patient care with a strong chemistry and biology foundation.'),
('Civil Engineering', '[90, 95, 78, 60, 60, 72]', 'Build infrastructure and solve large-scale engineering challenges in construction and public works.'),
('Mechanical Engineering', '[91, 93, 77, 66, 61, 71]', 'Focus on machines, manufacturing systems, and thermodynamics for industrial problem solving.'),
('Electrical Engineering', '[90, 94, 76, 72, 62, 70]', 'Work with circuits, power systems, electronics, and control technologies.'),
('Psychology', '[82, 78, 90, 60, 70, 75]', 'Study human behavior, mental processes, and social interactions in academic and applied settings.'),
('Architecture', '[82, 86, 80, 66, 68, 72]', 'Design built environments and space planning with a balance of creativity, technical drawing, and problem solving.'),
('Criminology', '[70, 79, 90, 58, 76, 88]', 'Examine crime, justice systems, and social behavior with strong analytical and communication skills.'),
('Tourism Management', '[68, 72, 88, 62, 92, 84]', 'Prepare for service, hospitality, and destination management roles in the travel and tourism sector.'),
('Education', '[72, 78, 92, 60, 68, 85]', 'Develop teaching abilities, communication, and instructional planning for academic and community learning.'),
('Early Childhood Education', '[74, 82, 92, 58, 66, 88]', 'Guide young learners through developmental, emotional, and literacy-based education practices.'),
('Agriculture', '[76, 94, 72, 60, 64, 68]', 'Study crop production, environmental systems, and resource management for sustainable agriculture.'),
('Fisheries', '[74, 92, 70, 60, 62, 70]', 'Focus on aquatic resource management, habitat protection, and sustainable seafood production.'),
('Nutrition and Dietetics', '[78, 90, 82, 60, 70, 76]', 'Apply health science and food knowledge to improve community nutrition, wellness, and patient care.'),
('Radiologic Technology', '[80, 94, 74, 68, 62, 72]', 'Use imaging technology and patient care knowledge to support diagnosis and medical procedures.'),
('Respiratory Therapy', '[82, 93, 75, 68, 65, 72]', 'Support respiratory health through medical science, patient assessment, and therapeutic interventions.'),
('Hospitality Management', '[68, 72, 86, 63, 94, 82]', 'Train for service operations, guest relations, and leadership within hotels, events, and tourism enterprises.'),
('Public Administration', '[70, 76, 88, 62, 90, 80]', 'Understand governance, policy implementation, and public service management in civic organizations.'),
('Environmental Science', '[78, 96, 76, 68, 62, 74]', 'Study ecosystems, sustainability, and natural resource systems to address environmental challenges.'),
('Biology', '[80, 96, 78, 60, 64, 72]', 'Understand living systems, scientific inquiry, and biological processes across research and applied fields.'),
('Legal Management', '[72, 70, 88, 60, 90, 80]', 'Develop legal and business knowledge for compliance, workplace governance, and administrative roles.'),
('Political Science', '[70, 76, 90, 60, 84, 82]', 'Study governance, public policy, and civic systems with strong communication and analysis abilities.')
on conflict (course) do update set features = excluded.features, description = excluded.description;

-- 169 additional courses to bring the catalog to 200 total
insert into public.course_training_data (course, features, description) values
('Chemical Engineering', '[86, 97, 71, 73, 58, 69]', 'Apply engineering principles and technical design to solve real-world chemical process and plant design challenges.'),
('Industrial Engineering', '[90, 93, 80, 67, 57, 63]', 'Apply engineering principles and technical design to solve real-world manufacturing systems and process optimization challenges.'),
('Computer Engineering', '[91, 95, 81, 72, 65, 68]', 'Apply engineering principles and technical design to solve real-world hardware, embedded systems, and computing infrastructure challenges.'),
('Aerospace Engineering', '[93, 91, 76, 68, 66, 70]', 'Apply engineering principles and technical design to solve real-world aircraft and spacecraft systems design challenges.'),
('Geodetic Engineering', '[88, 96, 75, 67, 67, 64]', 'Apply engineering principles and technical design to solve real-world land surveying and geospatial measurement challenges.'),
('Mining Engineering', '[91, 97, 78, 73, 58, 67]', 'Apply engineering principles and technical design to solve real-world mineral extraction and mine safety systems challenges.'),
('Metallurgical Engineering', '[86, 96, 79, 66, 64, 68]', 'Apply engineering principles and technical design to solve real-world metal processing and materials transformation challenges.'),
('Sanitary Engineering', '[86, 89, 76, 69, 62, 70]', 'Apply engineering principles and technical design to solve real-world water, waste, and public sanitation systems challenges.'),
('Petroleum Engineering', '[86, 94, 72, 68, 62, 66]', 'Apply engineering principles and technical design to solve real-world oil and gas extraction and processing systems challenges.'),
('Mechatronics Engineering', '[87, 89, 80, 65, 59, 64]', 'Apply engineering principles and technical design to solve real-world robotics, automation, and control systems challenges.'),
('Biomedical Engineering', '[92, 92, 76, 72, 63, 69]', 'Apply engineering principles and technical design to solve real-world medical devices and healthcare technology challenges.'),
('Materials Engineering', '[94, 87, 74, 67, 64, 72]', 'Apply engineering principles and technical design to solve real-world material science and industrial applications challenges.'),
('Marine Engineering', '[93, 92, 73, 64, 58, 66]', 'Apply engineering principles and technical design to solve real-world ship propulsion and onboard mechanical systems challenges.'),
('Naval Architecture', '[92, 96, 80, 63, 58, 65]', 'Apply engineering principles and technical design to solve real-world ship hull design and marine vessel engineering challenges.'),
('Automotive Engineering', '[90, 96, 80, 73, 66, 69]', 'Apply engineering principles and technical design to solve real-world vehicle systems and automotive technology challenges.'),
('Railway Engineering', '[90, 95, 80, 70, 62, 66]', 'Apply engineering principles and technical design to solve real-world rail infrastructure and transport systems challenges.'),
('Renewable Energy Engineering', '[88, 93, 75, 70, 61, 70]', 'Apply engineering principles and technical design to solve real-world sustainable power generation systems challenges.'),
('Robotics Engineering', '[87, 95, 73, 67, 63, 71]', 'Apply engineering principles and technical design to solve real-world autonomous systems and robotic design challenges.'),
('Agricultural Engineering', '[90, 94, 81, 68, 57, 68]', 'Apply engineering principles and technical design to solve real-world farm machinery and agricultural systems design challenges.'),
('Food Engineering', '[85, 91, 79, 68, 65, 71]', 'Apply engineering principles and technical design to solve real-world food processing and production systems challenges.'),
('Environmental Engineering', '[87, 91, 81, 72, 62, 73]', 'Apply engineering principles and technical design to solve real-world pollution control and environmental systems design challenges.'),
('Telecommunications Engineering', '[94, 91, 71, 71, 58, 67]', 'Apply engineering principles and technical design to solve real-world communication networks and signal systems challenges.'),
('Instrumentation and Control Engineering', '[92, 87, 75, 68, 57, 63]', 'Apply engineering principles and technical design to solve real-world process automation and control systems challenges.'),
('Cybersecurity', '[79, 71, 75, 98, 67, 64]', 'Build practical skills in protecting networks, systems, and data from digital threats for modern technology-driven careers.'),
('Game Development', '[83, 75, 75, 89, 72, 66]', 'Build practical skills in interactive game design and programming for modern technology-driven careers.'),
('Animation', '[84, 69, 75, 92, 71, 71]', 'Build practical skills in digital animation and visual storytelling for modern technology-driven careers.'),
('Multimedia Arts', '[83, 71, 72, 99, 73, 71]', 'Build practical skills in digital media production across platforms for modern technology-driven careers.'),
('Library and Information Science', '[84, 78, 81, 93, 71, 61]', 'Build practical skills in organizing and managing information resources for modern technology-driven careers.'),
('Network and Communications Technology', '[85, 75, 72, 90, 70, 67]', 'Build practical skills in network infrastructure and communication systems for modern technology-driven careers.'),
('Cloud and Systems Administration', '[78, 75, 77, 92, 63, 63]', 'Build practical skills in cloud infrastructure and systems management for modern technology-driven careers.'),
('Digital Forensics', '[77, 77, 81, 90, 70, 71]', 'Build practical skills in digital evidence recovery and cybercrime investigation for modern technology-driven careers.'),
('Robotics and Automation', '[87, 73, 78, 90, 72, 62]', 'Build practical skills in automated systems and intelligent machines for modern technology-driven careers.'),
('Data Engineering', '[83, 75, 78, 95, 64, 68]', 'Build practical skills in data pipelines and large-scale data infrastructure for modern technology-driven careers.'),
('Information Security Management', '[77, 77, 80, 99, 64, 70]', 'Build practical skills in organizational security policy and risk management for modern technology-driven careers.'),
('Human Resource Management', '[67, 70, 84, 65, 96, 69]', 'Develop workforce planning and organizational development expertise for leadership roles in modern organizations.'),
('Financial Management', '[67, 63, 80, 64, 99, 69]', 'Develop corporate finance and investment decision-making expertise for leadership roles in modern organizations.'),
('Entrepreneurship', '[75, 65, 87, 66, 99, 69]', 'Develop business creation and venture management expertise for leadership roles in modern organizations.'),
('Real Estate Management', '[69, 72, 80, 71, 96, 71]', 'Develop property development and real estate operations expertise for leadership roles in modern organizations.'),
('Supply Chain Management', '[68, 69, 77, 71, 99, 74]', 'Develop logistics coordination and supply network optimization expertise for leadership roles in modern organizations.'),
('Logistics Management', '[76, 66, 77, 68, 96, 72]', 'Develop distribution, warehousing, and transport operations expertise for leadership roles in modern organizations.'),
('Actuarial Science', '[73, 72, 84, 71, 99, 78]', 'Develop risk assessment and statistical financial modeling expertise for leadership roles in modern organizations.'),
('Economics', '[68, 68, 78, 65, 95, 72]', 'Develop market behavior and economic policy analysis expertise for leadership roles in modern organizations.'),
('Customs Administration', '[77, 65, 86, 61, 97, 70]', 'Develop trade regulation and customs compliance expertise for leadership roles in modern organizations.'),
('Office Administration', '[71, 64, 81, 61, 96, 76]', 'Develop administrative operations and office management expertise for leadership roles in modern organizations.'),
('Operations Management', '[72, 68, 79, 64, 94, 78]', 'Develop process efficiency and production management expertise for leadership roles in modern organizations.'),
('Retail Management', '[70, 66, 79, 71, 98, 78]', 'Develop merchandising and retail store operations expertise for leadership roles in modern organizations.'),
('International Business', '[71, 67, 81, 61, 91, 70]', 'Develop global trade and cross-border business strategy expertise for leadership roles in modern organizations.'),
('Cooperative Management', '[67, 63, 82, 71, 91, 74]', 'Develop cooperative enterprise governance and development expertise for leadership roles in modern organizations.'),
('Agribusiness Management', '[67, 64, 86, 68, 93, 77]', 'Develop agricultural enterprise and market management expertise for leadership roles in modern organizations.'),
('Insurance', '[70, 68, 84, 61, 99, 75]', 'Develop risk pooling and insurance policy management expertise for leadership roles in modern organizations.'),
('Banking and Finance', '[72, 73, 83, 69, 96, 79]', 'Develop financial institutions and banking operations expertise for leadership roles in modern organizations.'),
('Investment Management', '[69, 69, 83, 69, 95, 70]', 'Develop portfolio strategy and asset management expertise for leadership roles in modern organizations.'),
('Business Economics', '[77, 67, 83, 65, 99, 69]', 'Develop applied economic analysis for business strategy expertise for leadership roles in modern organizations.'),
('Project Management', '[67, 72, 79, 64, 98, 73]', 'Develop planning and delivering organizational projects expertise for leadership roles in modern organizations.'),
('Business Analytics', '[75, 66, 83, 62, 95, 79]', 'Develop data-driven decision-making for business strategy expertise for leadership roles in modern organizations.'),
('Digital Marketing', '[75, 65, 85, 64, 95, 69]', 'Develop online branding and digital campaign management expertise for leadership roles in modern organizations.'),
('E-Commerce Management', '[71, 69, 80, 64, 96, 77]', 'Develop online retail platforms and digital storefronts expertise for leadership roles in modern organizations.'),
('Risk Management', '[76, 63, 78, 62, 96, 72]', 'Develop identifying and mitigating organizational risk expertise for leadership roles in modern organizations.'),
('Quality Management', '[73, 65, 86, 68, 99, 73]', 'Develop process quality assurance and continuous improvement expertise for leadership roles in modern organizations.'),
('Public Finance', '[67, 65, 79, 69, 99, 71]', 'Develop government budgeting and fiscal policy expertise for leadership roles in modern organizations.'),
('Taxation', '[77, 70, 80, 63, 92, 77]', 'Develop tax law, compliance, and planning expertise for leadership roles in modern organizations.'),
('Auditing', '[71, 66, 78, 70, 94, 71]', 'Develop financial verification and internal control review expertise for leadership roles in modern organizations.'),
('Non-Profit Management', '[74, 70, 85, 70, 94, 75]', 'Develop leading mission-driven and charitable organizations expertise for leadership roles in modern organizations.'),
('Dentistry', '[77, 90, 74, 59, 64, 73]', 'Prepare for patient-centered careers through oral health diagnosis and dental care.'),
('Physical Therapy', '[80, 89, 81, 63, 64, 74]', 'Prepare for patient-centered careers through movement rehabilitation and physical recovery.'),
('Occupational Therapy', '[81, 96, 75, 59, 63, 78]', 'Prepare for patient-centered careers through functional rehabilitation for daily living skills.'),
('Speech-Language Pathology', '[83, 94, 78, 62, 72, 72]', 'Prepare for patient-centered careers through communication and swallowing disorder treatment.'),
('Optometry', '[80, 88, 73, 67, 68, 74]', 'Prepare for patient-centered careers through vision care and eye health management.'),
('Veterinary Medicine', '[77, 88, 78, 67, 69, 75]', 'Prepare for patient-centered careers through animal health diagnosis and treatment.'),
('Midwifery', '[82, 95, 82, 62, 69, 75]', 'Prepare for patient-centered careers through maternal and newborn care services.'),
('Public Health', '[85, 94, 78, 66, 69, 77]', 'Prepare for patient-centered careers through community health promotion and disease prevention.'),
('Biomedical Science', '[80, 92, 83, 63, 63, 70]', 'Prepare for patient-centered careers through laboratory science supporting medical diagnostics.'),
('Health Information Management', '[81, 96, 83, 58, 65, 74]', 'Prepare for patient-centered careers through medical records and health data systems.'),
('Sports Science', '[76, 91, 73, 66, 64, 72]', 'Prepare for patient-centered careers through human performance and athletic conditioning.'),
('Audiology', '[85, 87, 81, 64, 72, 70]', 'Prepare for patient-centered careers through hearing assessment and auditory care.'),
('Anesthesia Technology', '[76, 96, 78, 68, 67, 70]', 'Prepare for patient-centered careers through surgical support and anesthesia monitoring.'),
('Emergency Medical Services', '[79, 92, 78, 62, 73, 69]', 'Prepare for patient-centered careers through prehospital emergency care and response.'),
('Dental Hygiene', '[79, 91, 74, 63, 63, 70]', 'Prepare for patient-centered careers through preventive oral care and dental hygiene practice.'),
('Health Administration', '[85, 90, 73, 62, 70, 73]', 'Prepare for patient-centered careers through healthcare facility operations and management.'),
('Biostatistics', '[81, 89, 79, 65, 73, 77]', 'Prepare for patient-centered careers through statistical analysis for health research.'),
('Clinical Psychology', '[77, 89, 74, 68, 68, 70]', 'Prepare for patient-centered careers through mental health assessment and therapeutic care.'),
('Secondary Education - Mathematics', '[77, 76, 92, 64, 69, 87]', 'Study teaching mathematics at the secondary level to prepare for community-focused and academic careers.'),
('Secondary Education - Science', '[70, 73, 95, 60, 67, 84]', 'Study teaching science at the secondary level to prepare for community-focused and academic careers.'),
('Secondary Education - English', '[72, 75, 93, 57, 71, 89]', 'Study teaching English language and literature to prepare for community-focused and academic careers.'),
('Secondary Education - Filipino', '[76, 72, 94, 58, 71, 91]', 'Study teaching Filipino language and literature to prepare for community-focused and academic careers.'),
('Secondary Education - Social Studies', '[71, 74, 85, 64, 66, 85]', 'Study teaching history and social studies to prepare for community-focused and academic careers.'),
('Physical Education', '[73, 69, 91, 59, 66, 90]', 'Study teaching physical fitness and sports education to prepare for community-focused and academic careers.'),
('Special Needs Education', '[71, 79, 88, 57, 68, 85]', 'Study inclusive teaching for learners with special needs to prepare for community-focused and academic careers.'),
('Technology and Livelihood Education', '[68, 71, 85, 57, 74, 86]', 'Study teaching practical and vocational skills to prepare for community-focused and academic careers.'),
('Values Education', '[68, 75, 93, 57, 72, 86]', 'Study teaching ethics and character formation to prepare for community-focused and academic careers.'),
('Educational Management', '[70, 73, 89, 57, 73, 83]', 'Study school leadership and academic administration to prepare for community-focused and academic careers.'),
('Guidance and Counseling', '[77, 76, 87, 55, 68, 90]', 'Study student counseling and psychosocial support to prepare for community-focused and academic careers.'),
('Sociology', '[75, 74, 87, 65, 67, 83]', 'Study social structures and human group behavior to prepare for community-focused and academic careers.'),
('Anthropology', '[71, 71, 85, 60, 65, 88]', 'Study human culture and societal development to prepare for community-focused and academic careers.'),
('History', '[70, 77, 92, 55, 69, 83]', 'Study historical research and analysis of past events to prepare for community-focused and academic careers.'),
('Philosophy', '[73, 75, 93, 59, 73, 84]', 'Study critical thinking and philosophical inquiry to prepare for community-focused and academic careers.'),
('Communication', '[69, 77, 93, 64, 71, 91]', 'Study media, journalism, and public communication to prepare for community-focused and academic careers.'),
('Broadcasting', '[71, 76, 88, 60, 73, 90]', 'Study radio and television production and hosting to prepare for community-focused and academic careers.'),
('Public Relations', '[77, 75, 90, 65, 68, 87]', 'Study reputation management and strategic communication to prepare for community-focused and academic careers.'),
('Social Work', '[73, 76, 87, 59, 72, 84]', 'Study social services and community welfare support to prepare for community-focused and academic careers.'),
('International Studies', '[71, 75, 92, 61, 68, 89]', 'Study global affairs and cross-cultural relations to prepare for community-focused and academic careers.'),
('Development Studies', '[76, 69, 86, 65, 65, 85]', 'Study social and economic development strategies to prepare for community-focused and academic careers.'),
('Geography', '[68, 70, 86, 58, 68, 83]', 'Study spatial analysis of physical and human environments to prepare for community-focused and academic careers.'),
('Linguistics', '[73, 78, 93, 64, 72, 93]', 'Study language structure and communication science to prepare for community-focused and academic careers.'),
('Theology', '[71, 76, 95, 64, 66, 87]', 'Study religious studies and spiritual formation to prepare for community-focused and academic careers.'),
('Gender Studies', '[69, 74, 85, 55, 73, 83]', 'Study gender roles and social equity research to prepare for community-focused and academic careers.'),
('Human Services', '[73, 70, 89, 59, 65, 93]', 'Study direct support services for community welfare to prepare for community-focused and academic careers.'),
('Political Economy', '[69, 76, 87, 61, 69, 87]', 'Study the relationship between politics and economic systems to prepare for community-focused and academic careers.'),
('Community Development', '[77, 69, 86, 63, 71, 93]', 'Study grassroots organizing and community empowerment to prepare for community-focused and academic careers.'),
('Chemistry', '[87, 91, 71, 68, 61, 70]', 'Explore chemical reactions and molecular science through rigorous scientific inquiry and research.'),
('Biochemistry', '[86, 98, 73, 71, 61, 62]', 'Explore chemical processes within living organisms through rigorous scientific inquiry and research.'),
('Meteorology', '[88, 99, 70, 70, 56, 65]', 'Explore weather systems and atmospheric science through rigorous scientific inquiry and research.'),
('Astronomy', '[82, 95, 73, 70, 65, 69]', 'Explore celestial bodies and the physics of the universe through rigorous scientific inquiry and research.'),
('Mathematics', '[88, 99, 79, 69, 62, 62]', 'Explore abstract reasoning and mathematical theory through rigorous scientific inquiry and research.'),
('Applied Physics', '[84, 98, 76, 62, 58, 63]', 'Explore practical applications of physical science through rigorous scientific inquiry and research.'),
('Molecular Biology', '[89, 99, 71, 62, 61, 69]', 'Explore molecular mechanisms of biological systems through rigorous scientific inquiry and research.'),
('Genetics', '[84, 99, 79, 70, 65, 65]', 'Explore heredity and genetic variation research through rigorous scientific inquiry and research.'),
('Food Science and Technology', '[88, 93, 78, 65, 61, 67]', 'Explore food safety, quality, and processing science through rigorous scientific inquiry and research.'),
('Forensic Chemistry', '[88, 93, 69, 65, 63, 70]', 'Explore chemical analysis for criminal investigations through rigorous scientific inquiry and research.'),
('Forestry', '[77, 94, 77, 60, 68, 66]', 'Study forest resource management and conservation for careers in sustainable resource management.'),
('Agroforestry', '[76, 90, 70, 63, 71, 66]', 'Study integrated tree and crop production systems for careers in sustainable resource management.'),
('Animal Science', '[72, 88, 68, 56, 71, 67]', 'Study livestock production and animal husbandry for careers in sustainable resource management.'),
('Agricultural Economics', '[80, 89, 69, 60, 71, 67]', 'Study farm business and agricultural market analysis for careers in sustainable resource management.'),
('Horticulture', '[77, 90, 70, 56, 70, 72]', 'Study fruit, vegetable, and ornamental plant production for careers in sustainable resource management.'),
('Soil Science', '[74, 93, 69, 56, 69, 69]', 'Study soil health and land productivity management for careers in sustainable resource management.'),
('Aquaculture', '[75, 95, 67, 63, 64, 73]', 'Study fish and aquatic organism farming for careers in sustainable resource management.'),
('Marine Science', '[75, 92, 73, 62, 65, 66]', 'Study oceanography and marine resource studies for careers in sustainable resource management.'),
('Wildlife Management', '[73, 97, 71, 59, 68, 66]', 'Study conservation of wildlife populations and habitats for careers in sustainable resource management.'),
('Sustainable Development', '[71, 87, 70, 64, 64, 63]', 'Study balancing environmental, social, and economic growth for careers in sustainable resource management.'),
('Landscape Architecture', '[77, 87, 76, 61, 67, 68]', 'Study designing outdoor and environmental spaces for careers in sustainable resource management.'),
('Fine Arts', '[72, 61, 80, 69, 69, 77]', 'Cultivate creative skills in visual art creation and studio practice for design and media careers.'),
('Graphic Design', '[68, 62, 81, 69, 62, 74]', 'Cultivate creative skills in visual communication and branding design for design and media careers.'),
('Interior Design', '[71, 67, 79, 75, 65, 74]', 'Cultivate creative skills in functional and aesthetic interior space planning for design and media careers.'),
('Fashion Design', '[70, 62, 88, 72, 63, 80]', 'Cultivate creative skills in clothing design and textile arts for design and media careers.'),
('Industrial Design', '[68, 67, 87, 69, 65, 79]', 'Cultivate creative skills in product design and manufacturing aesthetics for design and media careers.'),
('Film and Media Studies', '[65, 69, 88, 72, 67, 78]', 'Cultivate creative skills in film production and media analysis for design and media careers.'),
('Theater Arts', '[64, 66, 86, 66, 61, 81]', 'Cultivate creative skills in stage performance and dramatic arts for design and media careers.'),
('Music', '[63, 61, 79, 74, 66, 82]', 'Cultivate creative skills in musical performance, theory, and composition for design and media careers.'),
('Dance', '[65, 62, 85, 74, 62, 80]', 'Cultivate creative skills in choreography and performance arts for design and media careers.'),
('Photography', '[65, 62, 86, 69, 62, 75]', 'Cultivate creative skills in visual storytelling through photographic art for design and media careers.'),
('Creative Writing', '[63, 63, 89, 74, 65, 76]', 'Cultivate creative skills in fiction, poetry, and narrative craft for design and media careers.'),
('Literature', '[67, 69, 84, 66, 65, 74]', 'Cultivate creative skills in literary analysis and critical reading for design and media careers.'),
('Culture and Arts Management', '[68, 61, 89, 70, 61, 77]', 'Cultivate creative skills in managing cultural institutions and creative programs for design and media careers.'),
('Museum Studies', '[73, 65, 87, 69, 68, 77]', 'Cultivate creative skills in curatorship and museum operations for design and media careers.'),
('Translation and Interpretation', '[73, 71, 83, 72, 64, 78]', 'Cultivate creative skills in cross-language communication and localization for design and media careers.'),
('Culinary Arts', '[65, 73, 90, 62, 87, 81]', 'Train for professional cooking and kitchen management within the hospitality and travel industry.'),
('Baking and Pastry Arts', '[63, 73, 88, 57, 88, 75]', 'Train for bread, pastry, and dessert production within the hospitality and travel industry.'),
('Cruise Line Operations', '[68, 72, 90, 65, 96, 84]', 'Train for hospitality services aboard cruise ships within the hospitality and travel industry.'),
('Event Management', '[66, 71, 86, 67, 97, 80]', 'Train for planning and executing large-scale events within the hospitality and travel industry.'),
('Travel Operations Management', '[68, 69, 85, 63, 96, 77]', 'Train for travel agency and tour operations within the hospitality and travel industry.'),
('Resort Management', '[72, 67, 82, 65, 93, 78]', 'Train for resort facility and guest service operations within the hospitality and travel industry.'),
('Airline Operations', '[67, 72, 89, 60, 91, 76]', 'Train for airline ground and passenger service operations within the hospitality and travel industry.'),
('Aviation Management', '[68, 75, 83, 63, 93, 81]', 'Train for airport and aviation business operations within the hospitality and travel industry.'),
('Air Traffic Management', '[69, 69, 81, 59, 91, 75]', 'Train for coordinating safe and efficient air traffic within the hospitality and travel industry.'),
('Forensic Science', '[66, 74, 84, 65, 91, 79]', 'Prepare for scientific analysis for criminal justice investigations careers serving communities and institutions.'),
('Criminal Justice', '[65, 71, 93, 66, 92, 82]', 'Prepare for law enforcement and justice system administration careers serving communities and institutions.'),
('Disaster Risk Management', '[75, 71, 85, 61, 84, 84]', 'Prepare for emergency preparedness and disaster response planning careers serving communities and institutions.'),
('Renewable Energy Management', '[67, 78, 85, 57, 89, 84]', 'Prepare for sustainable energy policy and project management careers serving communities and institutions.'),
('Marine Transportation', '[69, 80, 84, 57, 90, 84]', 'Prepare for maritime navigation and ship operations careers serving communities and institutions.'),
('Physical Fitness and Recreation Management', '[74, 73, 89, 62, 86, 85]', 'Prepare for recreation programs and fitness facility management careers serving communities and institutions.')
on conflict (course) do update set features = excluded.features, description = excluded.description;

-- Reuse the existing academic feature profiles, then retain only university programs.
create temporary table if not exists university_course_catalog (
    course text primary key,
    source text not null
);
truncate university_course_catalog;
insert into university_course_catalog (course, source) values
('BS in Medical Technology', 'Medical Technology'),
('BS in Nursing', 'Nursing'),
('BS in Occupational Therapy', 'Occupational Therapy'),
('BS in Pharmacy', 'Pharmacy'),
('BS in Physical Therapy', 'Physical Therapy'),
('BS in Radiologic Technology', 'Radiologic Technology'),
('BS in Respiratory Therapy', 'Respiratory Therapy'),
('BS in Architecture', 'Architecture'),
('Bachelor of Arts in Communication', 'Communication'),
('Bachelor of Arts major in Political Science', 'Political Science'),
('Bachelor of Arts in Psychology', 'Psychology'),
('Bachelor of Arts in Multimedia Arts', 'Multimedia Arts'),
('Bachelor of Science in Psychology', 'Psychology'),
('BS in Aircraft Maintenance and Technology', 'Mechanical Engineering'),
('BS in Aviation Electronics Technology', 'Electrical Engineering'),
('Aircraft Maintenance Technology', 'Mechanical Engineering'),
('Aviation Electronics Technology', 'Electrical Engineering'),
('BS in Accountancy', 'Accountancy'),
('BS in Business Administration', 'Business Administration'),
('BS in Business Administration major in Human Resource Management', 'Human Resource Management'),
('BS in Business Administration major in Marketing Management', 'Marketing Management'),
('BS in Entrepreneurship', 'Entrepreneurship'),
('BS in Criminology', 'Criminology'),
('BS in Aeronautical Engineering', 'Aerospace Engineering'),
('BS in Civil Engineering', 'Civil Engineering'),
('BS in Mechanical Engineering', 'Mechanical Engineering'),
('BS in Computer Engineering', 'Computer Engineering'),
('BS in Digital Engineering', 'Data Engineering'),
('BS in Electrical Engineering', 'Electrical Engineering'),
('BS in Electronics Engineering major in Biomedical Engineering', 'Biomedical Engineering'),
('BS in Industrial Engineering', 'Industrial Engineering'),
('BS in Information Technology with Specialization in Game Development', 'Game Development'),
('BS in Computer Science with Specialization in Data Science', 'Data Science'),
('Bachelor of Library and Information Science', 'Library and Information Science'),
('BS in Tourism Management', 'Tourism Management'),
('BS in Hospitality Management', 'Hospitality Management'),
('BS in Marine Transportation', 'Marine Transportation'),
('BS in Marine Engineering', 'Marine Engineering'),
('BS in Naval Architecture and Marine Engineering', 'Naval Architecture'),
('Bachelor of Early Childhood Education', 'Early Childhood Education'),
('Bachelor of Elementary Education', 'Early Childhood Education'),
('Bachelor of Physical Education', 'Physical Education'),
('Bachelor of Secondary Education', 'Secondary Education - Mathematics'),
('Bachelor of Special Needs Education', 'Special Needs Education');

insert into public.course_training_data (course, features, description)
select catalog.course, source.features,
    case catalog.course
        when 'BS in Aircraft Maintenance and Technology' then 'Study aircraft inspection, maintenance, and repair for safe aviation operations.'
        when 'Aircraft Maintenance Technology' then 'Study aircraft inspection, maintenance, and repair for safe aviation operations.'
        when 'BS in Aviation Electronics Technology' then 'Study aircraft electrical systems, avionics, and aviation electronics maintenance.'
        when 'Aviation Electronics Technology' then 'Study aircraft electrical systems, avionics, and aviation electronics maintenance.'
        when 'Bachelor of Elementary Education' then 'Prepare to teach and support learners across elementary school subjects.'
        when 'Bachelor of Secondary Education' then 'Prepare to teach and support learners at the secondary school level.'
        when 'BS in Digital Engineering' then 'Apply digital tools, data, and engineering methods to design technical systems.'
        when 'BS in Naval Architecture and Marine Engineering' then 'Study ship design, vessel structures, and marine engineering systems.'
        else source.description
    end
from university_course_catalog catalog
join public.course_training_data source on source.course = catalog.source
on conflict (course) do update set features = excluded.features, description = excluded.description;

delete from public.course_training_data
where course not in (select course from university_course_catalog);
drop table university_course_catalog;
